# Generated by Django 2.2.13 on 2020-07-15 19:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_email', '0003_emaillog_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Extra parameters passed to the Message object', null=True),
        ),
    ]
