# Generated by Django 3.0.5 on 2020-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_email', '0004_auto_20200715_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='extra',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='reply_to',
            field=models.EmailField(blank=True, help_text='The Reply-to email address', max_length=254, null=True),
        ),
    ]
